[bumpver]
current_version = "2024.10.11-1003"
version_pattern = "YYYY.0M.0D-BUILD"
commit_message = "bump version to {new_version}"
commit = true
tag = true
push = false

[bumpver.file_patterns]
"bumpver.toml" = [
    'current_version = "{version}"',
]
