version: '2'
services:
  kannel:
    build: .
    entrypoint:
      - /usr/sbin/bearerbox
      - /etc/kannel/kannel.conf
  smsbox:
    build: .
    entrypoint:
      - /usr/sbin/smsbox
      - /etc/kannel/kannel.conf
    links:
      - kannel:bearerbox
    ports:
      - "13013:13013"
